In [1]:
%matplotlib inline

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## brocasting

In [2]:
np.array([3, 4, 5, 9, 12]) + 5

array([ 8,  9, 10, 14, 17])

In [3]:
mygrades = np.array([89, 99, 60])

In [4]:
weights = np.array([0.3, 0.4, 0.3])

In [5]:
mygrades * weights

array([26.7, 39.6, 18. ])

In [6]:
g = mygrades * weights

In [7]:
g.sum()

84.3

In [9]:
np.dot(mygrades, weights) #內積

84.3

In [11]:
mygrades @ weights #內積

84.3

## 不同shape轉換

### 0階 array (0階 tensor)

In [13]:
egg = 94.87

### 1階 array (1階 tensor)

In [14]:
egg = np.array([9, 4, 8, 7])

### 2階 array (2階 tensor)

In [18]:
A = np.array([[1, 2, 3], [4, 5, 6]])

In [19]:
A

array([[1, 2, 3],
       [4, 5, 6]])

In [20]:
B = np.array([3, 9, 6, 12, 8, 20, 1, 10, 7]) 

In [21]:
B

array([ 3,  9,  6, 12,  8, 20,  1, 10,  7])

In [22]:
A.shape

(2, 3)

In [23]:
B.shape

(9,)

In [26]:
B.reshape(3,3)

array([[ 3,  9,  6],
       [12,  8, 20],
       [ 1, 10,  7]])

In [27]:
B

array([ 3,  9,  6, 12,  8, 20,  1, 10,  7])

In [28]:
B = B.reshape(3, 3)

In [29]:
B

array([[ 3,  9,  6],
       [12,  8, 20],
       [ 1, 10,  7]])

In [30]:
A @ B  #A的列乘B的行相加

array([[ 30,  55,  67],
       [ 78, 136, 166]])

In [31]:
C = A@B

In [32]:
C

array([[ 30,  55,  67],
       [ 78, 136, 166]])

In [33]:
C[1] #行列也是從0開始編號

array([ 78, 136, 166])

In [34]:
C[1, 1]

136

In [35]:
C[ : , 2]

array([ 67, 166])